stages:
 - deploy

deploy:
 stage: deploy
 image: docker:20.10.16
 before_script:
 - apk add --no-cache openssh-client git
 - mkdir -p ~/.ssh
 - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
 - chmod 600 ~/.ssh/id_rsa
 - eval $(ssh-agent -s)
 - ssh-add ~/.ssh/id_rsa
 - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
 script:
 # Check the directory structure first
 - |
   ssh $SSH_USER@$SSH_HOST "
   echo 'Checking directory structure:'
   ls -la /var/www/html/
   echo '-------------------'
   if [ -d /var/www/html/memora ]; then
     echo 'Directory /var/www/html/memora exists, checking content:'
     ls -la /var/www/html/memora/
   else
     echo 'Directory /var/www/html/memora does NOT exist!'
   fi
   echo '-------------------'
   echo 'Checking for docker-compose:'
   which docker-compose || echo 'docker-compose not found'
   "
 only:
 - main