stages:
 - deploy

deploy:
 stage: deploy
 image: docker:20.10.16
 before_script:
 - apk add --no-cache openssh-client git
 - mkdir -p ~/.ssh
 # Write the key to a file with proper line breaks
 - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
 - chmod 600 ~/.ssh/id_rsa
 - eval $(ssh-agent -s)
 - ssh-add ~/.ssh/id_rsa
 - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
 script:
 # Skip the file copy and go straight to repository updates
 - |
   ssh $SSH_USER@$SSH_HOST "
   cd /var/www/html/memora
   # Pull orchestrating repo
   cd ./docker-compose-config && git pull && cd ..
   # Pull backend repo
   cd ./memora_back_end && git pull && cd ..
   # Pull frontend repo
   cd ./memora_front_end && git pull && cd ..
   # Navigate to orchestration directory and start the application
   cd /var/www/html/memora/docker-compose-config
   docker-compose up -d --build
   "
 only:
 - main